### PR TITLE
Better distuingish which file can and cannot by compiled with C compiler.

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

# Pull request

**Choose Correct**

- [ ] bug
- [X] feature

**Describe the pull request**

Renaming C++ header files extensions from .h to .hpp. This can inform programers which header files shouldn't be compiled with C compiler (do not include in .c files). 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [X] PR code is tested. -> The part which i can test.
- [X] PR code is formatted.

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
@MichalPrincNXP I believe this is ready for merge

**Comment by MichalPrincNXP** [comment]
There are several unit test sources where the workaround for Compiler redefinition errors in arm_compat.h have been applied recently. This is related to the update to CMSIS 5.8.0 in the MCUXpressoSDK.
- ensure the arm_compat.h is included before the CMSIS compliant device-specific header file, in our case the rpmsg_compiler.h needs to be included as first where needed
- Article ID: KA004795 on developer.arm.com

Could you please keep the include order in following files?
unit_test_server.cpp
unit_test_client.cpp
unit_test_arbitrator_app0.cpp
unit_test_arbitrator_app1.cpp

**Comment by MichalPrincNXP** [comment]
> Is it ok now?

Yes, thanks,  I am still testing on boards ...

**Review by MichalPrincNXP — APPROVED** [review]
Onboard testing finished, just a minor update in unit_test_client.cpp needed:
gtestListener.h -> gtestListener.hpp
myAlloc.h -> myAlloc.hpp

**Comment by MichalPrincNXP** [comment]
Thank you, Dusan

**Pull request merged**
