### PR TITLE
Fix corrupt clientList bug in TransportArbitrator

### PR DESCRIPTION
**Pull request by ramlco**
If m_clientList is null and m_clientFreeList has more than one node, m_clientList->m_next will point back to m_clientFreeList.  This results in an error in the destructor.  Always setting 'info->m_next = m_clientList' fixes the issue

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @ramlco , thank for this PR with the bugfix. I am ok with these changes but could you please format the code correctly (see https://github.com/EmbeddedRPC/erpc/wiki/Contributing) - there are tabs in changed lines. And, also could you please rebase to the develop head (it seems failing greetings action blocks consequent Travis build check). Thank you.

**Review by Hadatko — APPROVED** [review]
I am approving this PR. 
As code wasn't formatted properly so far, we can merge it and format internally or ignore it and do internally. First case sounds better as it should be benefit of owner of the change.

**Review by Hadatko — APPROVED** [review]
I fixed indention. So i think it is ready for merge. @MichalPrincNXP

**Review by MichalPrincNXP — APPROVED** [review]
Thanks for your effort!

**Pull request merged**
