### PR TITLE
adding TCP_NODELAY socket flag

### PR DESCRIPTION
**Pull request by mentaal**
I had noticed that the transaction rate I was achieving in ERPC was very low, around 20 transactions/sec. 
After debugging the code and eliminating the code from being the source of the latency, I asked on SO what the problem could be and [Nagle's algorithm](https://en.wikipedia.org/wiki/Nagle%27s_algorithm) was suggested as being a culprit. This makes sense as ERPC's header transmission is very small.

See the full legwork in the SO question [here](https://stackoverflow.com/questions/50930865/finding-the-source-of-latency-in-an-rpc-system).

With this change my transaction rate went from ~20 to 2500+.

### CODE REVIEW

**Comment by mentaal** [comment]
mmm is netinet/tcp.h not present in the build environment?

**Comment by Hadatko** [comment]
Mac OSx issue. Sorry.

**Comment by mentaal** [comment]
Any ideas on what I can do to get this branch working regarding tests?

**Comment by Hadatko** [comment]
In a link i sent you they made this:
 #ifndef SOL_TCP
 #define SOL_TCP IPPROTO_TCP
 #endif
I am not sure if it is best solution. What do you think?

**Comment by mentaal** [comment]
Good point. I didn't know it was a linux specific option. That sounds like a good way to go about it. 
(Here's a related SO question: https://stackoverflow.com/questions/12112310/is-there-a-way-to-access-the-sol-tcp-aka-ipproto-tcp-socket-options-e-g-tcp) 
I'll make the change

**Comment by SASIDHARAN-dot** [comment]
TCP_NODELAY has to set on both client and server socket.

**Comment by pgu-swir** [comment]
I don't think this sets client & server - the change I've proposed does both

**Comment by Hadatko** [comment]
@pgu-swir as you can see above we had issue with MAC OS and TCP_NODELAY. Which was solved here. Did you PR contains that too?

**Comment by pgu-swir** [comment]
I think because I've used IPPROTO_TCP directly and not SOL_TCP, this is defined as well on MacOS. I'm also ignoring the result of setsockopt because I don't think we want to fail if TCP_NODELAY cannot be set

**Comment by Hadatko** [comment]
Hi @MichalPrincNXP i think this can be closed now. But we may want one python line which is in this PR

**Pull request closed without merging**
