### PR TITLE
run_clang_format.py cleanup

### PR DESCRIPTION
**Pull request by dpfrey**

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @dpfrey , thank you for this PR. I have two comments/questions:
- What is the first command about (Make run_clang_format.py executable)? I do not see any difference.
- I would stay with "subprocess.call(["clang-format-10.0", "-i", file])"  - thus users are informed again that the v10.0 needs to be used, maybe the description in https://github.com/EmbeddedRPC/erpc/wiki/Contributing could be updated to be more accurate about install folder naming / script content renaming

**Comment by dpfrey** [comment]
Thanks for taking a look at this @MichalPrincNXP.

git tracks file permissions. So prior to this PR, if someone clones eRPC, the `run_clang_format.py` will not have the executable permission and therefore it will not be possible to do:
```
$ ./run_clang_format.py
```
The user must either run:
```
$ python run_clang_format.py
```
or:
```
$ chmod a+x run_clang_format.py
$ ./run_clang_format.py
```
So it's basically just a minor ease of use change and it also helps to signal to the user that this python file is meant to be executed as a script rather than imported as a library.

I was previously building eRPC on arch linux and there was no `clang-format-10` binary, only `clang-format`. My Arch Linux install imploded and I have installed Ubuntu and it has `clang-format-10`. I guess `clang-format` might be better for compatibility than `clang-format-10`, but I guess that makes it less clear that version 10 is required.

**Comment by MichalPrincNXP** [comment]
Thank you, @dpfrey . Re. the way Clang version is checking, better approach would be runtime check, I think. I have updated the script by this runtime version checking ... may I ask you to try on your side, please? Thank you.
M.
[run_clang_format.zip](https://github.com/EmbeddedRPC/erpc/files/6746076/run_clang_format.zip)

**Comment by dpfrey** [comment]
Hi @MichalPrincNXP, I took the code from your zip file and modified it to allow any clang-format newer than 10.0.0.  I pushed a new commit on top of this PR that adds the version checking.

**Comment by MichalPrincNXP** [comment]
David, I would rather stick with 10.0.0 version. I have read that each version produces a littler different output and that is why one specified version would be preferred.

**Comment by Hadatko** [comment]
Hi @dpfrey it is really important to stick with one concrete version of clang-format application. Even minor version may provide different output. If users will change code with different clang-format application, they may change formatted code back and forth. This may result in redundant code format changes pushed to the repository.

**Comment by Hadatko** [comment]
Other changes looks great. Btw i would like to add this link to several places to let user know where to download binary [https://releases.llvm.org/download.html](https://releases.llvm.org/download.html).
Currently i think we are using clang-format from path environment. Maybe we should first check if exist variable CLANG_FORMAT_PATH. Users may use it to set path to downloaded clang-format.

**Comment by dpfrey** [comment]
Thanks for the feedback @Hadatko And @MichalPrincNXP. I agree that it would be a problem if a clang-format newer than 10.0 produced output different from 10.0.0.  In the latest commit, I require clang-format == 10.0.0 and I also made `$CLANG_FORMAT_PATH` the first choice and `"clang-format"` the backup.

**Comment by MichalPrincNXP** [comment]
Great, thank you @dpfrey !

**Pull request merged**
