### PR TITLE
Python 'inout' parameter support - #44

### PR DESCRIPTION
**Pull request by nchokoev**
This should solve the issue.

### CODE REVIEW

**Comment by Hadatko** [comment]
Hi @nchokoev,
thank you for pull request. Once i will be again focused on eRPC i will review your commit.

**Comment by Hadatko** [comment]
Hi @nchokoev , it looks like you fixed issue only in encoder. Do you think decoder is working correctly?

**Comment by nchokoev** [comment]
Hi @Hadatko,
I think it's ok, bit it's been a long time. I have to double check.

**Comment by Hadatko** [comment]
Thank you for your PR @nchokoev but i did new implementation in #237.

**Pull request closed without merging**
