### PR TITLE
VS build

### PR DESCRIPTION
**Pull request by Hadatko**
# Pull request

**Choose Correct**

- [ ] bug
- [X] feature

**Describe the pull request**

build VS project

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [X] PR code is tested.
- [X] PR code is formatted.
- [X] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
This looks working too. I disabled some artefacts as we don't need two apps per OS just one. Consider merge after: https://github.com/EmbeddedRPC/erpc/pull/344

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by Hadatko** [comment]
Hi @MichalPrincNXP are you solving merge conflicts by yourself?

**Comment by MichalPrincNXP** [comment]
> Hi @MichalPrincNXP are you solving merge conflicts by yourself?

Yes, sorry I already did it, however, the automatic merge of erpcgen\Makefile is not correct, may you please update it again, I am sorry for confusion.

**Comment by MichalPrincNXP** [comment]
Thank you Dusan for the effort and sorry for the compilation with the merge.

**Pull request merged**
