### PR TITLE
Fix to compile a serial server on Linux with -Wall -Wextra -Wshadow -Werror -pedantic-errors flags

### PR DESCRIPTION
**Pull request by jcdr**
I use those C and C++ flags in my Makefile that trigg some compiler error:
FLAGS+=-Wall -Wextra -Wshadow -Werror -pedantic-errors -fdiagnostics-color -O6 -g
CFLAGS+=-std=gnu11 $(FLAGS)
CPPFLAGS+=-std=gnu++2a $(FLAGS)
The fixes allow to resolve the issues:
2 unused parameters
1 extra ;
1 timestamp.tv_ns not initialized

### CODE REVIEW

**Comment by Hadatko** [comment]
Thank you for the PR. Maybe you can update also makefiles with these flags within this commit. @MichalPrincNXP do you agree?

**Comment by jcdr** [comment]
This will probably force to use the -std=gnu++2a flag that are maybe not available to everyone stuck with a not recent compiler for some reason. With only -std=gnu++11 the -Wpedantic-error flag cause this issue:

In static member function ‘static void erpc::Thread::sleep(uint32_t)’:
erpc/erpc_c/port/erpc_threading_pthreads.cpp:86:28: error: C++ designated initializers only available with -std=c++2a or -std=gnu++2a [-Wpedantic]
     struct timespec rq = { .tv_sec = usecs / 1000000, .tv_nsec = (usecs % 1000000) * 1000 };
                            ^

**Comment by jcdr** [comment]
I have now a lot of issue like this:

In file included from /server/home/jcdr/try/erpc/erpcgen/src/types/Interface.h:13,
                 from /server/home/jcdr/try/erpc/erpcgen/src/SymbolScanner.h:17,
                 from /server/home/jcdr/try/erpc/erpcgen/src/SymbolScanner.cpp:11:
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h: In constructor ‘erpcgen::Function::Function(const erpcgen::Token&, erpcgen::Interface*)’:
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:132:29: error: base ‘erpcgen::Symbol’ will be initialized after [-Werror=reorder]
     , m_functionType(nullptr)
                             ^
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:132:29: error:   base ‘erpcgen::FunctionBase’ [-Werror=reorder]
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:127:5: error:   when initialized here [-Werror=reorder]
     Function(const Token &tok, Interface *interface)
     ^~~~~~~~
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h: In constructor ‘erpcgen::Function::Function(const erpcgen::Token&, erpcgen::Interface*, uint32_t)’:
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:150:29: error: base ‘erpcgen::Symbol’ will be initialized after [-Werror=reorder]
     , m_functionType(nullptr)
                             ^
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:150:29: error:   base ‘erpcgen::FunctionBase’ [-Werror=reorder]
/server/home/jcdr/try/erpc/erpcgen/src/types/Function.h:145:5: error:   when initialized here [-Werror=reorder]
     Function(const Token &tok, Interface *interface, uint32_t uniqueId)
     ^~~~~~~~

Don't have time now to solve that kind of issue.

**Comment by jcdr** [comment]
I have now a lot of issue like this:

In file included from erpc/erpcgen/src/types/Interface.h:13,
from erpc/erpcgen/src/SymbolScanner.h:17,
from erpc/erpcgen/src/SymbolScanner.cpp:11:
erpc/erpcgen/src/types/Function.h: In constructor ‘erpcgen::Function::Function(const erpcgen::Token&, erpcgen::Interface*)’:
erpc/erpcgen/src/types/Function.h:132:29: error: base ‘erpcgen::Symbol’ will be initialized after [-Werror=reorder]
, m_functionType(nullptr)
^
erpc/erpcgen/src/types/Function.h:132:29: error: base ‘erpcgen::FunctionBase’ [-Werror=reorder]
erpc/erpcgen/src/types/Function.h:127:5: error: when initialized here [-Werror=reorder]
Function(const Token &tok, Interface interface)
^~~~~~~~
erpc/erpcgen/src/types/Function.h: In constructor ‘erpcgen::Function::Function(const erpcgen::Token&, erpcgen::Interface, uint32_t)’:
erpc/erpcgen/src/types/Function.h:150:29: error: base ‘erpcgen::Symbol’ will be initialized after [-Werror=reorder]
, m_functionType(nullptr)
^
erpc/erpcgen/src/types/Function.h:150:29: error: base ‘erpcgen::FunctionBase’ [-Werror=reorder]
erpc/erpcgen/src/types/Function.h:145:5: error: when initialized here [-Werror=reorder]
Function(const Token &tok, Interface *interface, uint32_t uniqueId)
^~~~~~~~

Don't have time now to solve that kind of issue.

**Comment by jcdr** [comment]
At least it now compile with the paranoid flags but the -Werror=reorder issue have to be solved before this could be merged.
Anyone have an idea on how to solve it ?

**Comment by jcdr** [comment]
Ok, I finally find a way to fix the reorder issues. Probably require a careful check by someone else.
It compile on my machine, but maybe not on Travis.

**Comment by jcdr** [comment]
Obviously, this is a more ambitious fix than initially expected...

[/home/travis/build/EmbeddedRPC/erpc/test/test_annotations/Linux/tcp/gcc/test_annotations_client/Debug/erpc_outputs/test/client.py] Segmentation fault (core dumped)

I doubt that I will continue that way. Someone that understand more deeply the internal logic could get some hints from this and make better choices to properly fix the issues.

**Comment by jcdr** [comment]
I remastered everything into the pull request Paranoid #136

**Pull request closed without merging**
