### PR TITLE
Adding NULL to ptr when codec function failed.

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

### CODE REVIEW

**Comment by amgross** [comment]
I suggest to add comment in the code explaining the reason behind putting value in the pointer, as it not trivial

**Comment by amgross** [comment]
I think you wrote the word 'in' twice by mistake " 0 can be valid value or **in in** case of error."
Anyway I thought we agreed in the issue discussion that this solution is not enough?

**Comment by Hadatko** [comment]
HI @amgross , the last commit was related to your request with adding comment to code.
Final decision was not made related to memcpy.
What about replace memcpy with memmove?

**Comment by Hadatko** [comment]
@amgross what do you think about memcpy_s?

**Comment by amgross** [comment]
@Hadatko  I think memcpy_s will solve the issue. unfortunately it seems from the documentations that not all compilers includes this function.
['As with all bounds-checked functions, memcpy_s is only guaranteed to be available if __STDC_LIB_EXT1__ is defined by the implementation' ](https://en.cppreference.com/w/c/string/byte/memcpy)

**Review by amgross — APPROVED** [review]

**Comment by Hadatko** [comment]
@amgross Thank you for your collaboration.

@MichalPrincNXP likely ready.

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by MichalPrincNXP** [comment]
Thank you for the effort!

**Pull request merged**
