### PR TITLE
AllowShortFunctionsOnASingleLine was twice.

### PR DESCRIPTION
**Pull request by Hadatko**
-- Code style of document was confusing.
-- Added link to documentation for current version.

### CODE REVIEW

**Comment by Hadatko** [comment]
Any plans to move to the newer clang-format?

**Comment by MichalPrincNXP** [comment]
> 
> 
> Any plans to move to the newer clang-format?

It would be fine, let me try to format with clang V10 and test it internally. Once OK, I would switch to this V10 version.

**Review by MichalPrincNXP — APPROVED** [review]
great, thanks!

**Comment by MichalPrincNXP** [comment]
> 
> 
> > Any plans to move to the newer clang-format?
> 
> It would be fine, let me try to format with clang V10 and test it internally. Once OK, I would switch to this V10 version.

@Hadatko , testing with Clang V10 formatted code is OK, we can use it, I will provide an update early next week together with other changes for 1.8.0 release.

**Comment by Hadatko** [comment]
Do not forget update wiki, run_clang_format.py, and current new yaml which should format code automatically. Hope it will work now.

**Pull request merged**
