### PR TITLE
Feature/buffer head

### PR DESCRIPTION
**Pull request by Hadatko**
# Pull request

**Choose Correct**

- [ ] bug
- [x] feature

**Describe the pull request**

Thanks to this PR framed transport should be able to store header data in message buffer and all data can be send to other side at once. So far not tested. 

!!!!! Please review and merge this PR: https://github.com/EmbeddedRPC/erpc/pull/373

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [ ] PR code is tested.
- [X] PR code is formatted.
- [ ] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
@amgross  @MichalPrincNXP First non tested version for serializing and deserializing header data in MessageBuffer. What do you think? I will try to think if we can simplify things, but there is many scenario we need count with

**Comment by Hadatko** [comment]
Hmm tests are not passing, need to see where i have an issue.

**Comment by Hadatko** [comment]
@MichalPrincNXP Could you start with reviewing? As tests are passing most transport should work. What could be an issue are RPMSG related transports. I will try rpmsg tty implemenattion, but it would be great if you can some other rpmsg implementation on your side.

**Comment by Hadatko** [comment]
@MichalPrincNXP I provided simple fix for rpmsg tty. Tested on board. What i cannot test is MU and other RPMSG transports. Could you try at least some of them (e.g. MU). It would be great if we can confirm at least compilation for all of them and running test for at least one of them (e.g. MU)

**Comment by Hadatko** [comment]
Hi @MichalPrincNXP , as promissed PR rebased to the top...

**Review by MichalPrincNXP — APPROVED** [review]

**Pull request merged**
