### PR TITLE
remove defining parse.error which make errors while compiling erpcgen…

### PR DESCRIPTION
**Pull request by amgross**
remove defining parse.error which make errors while compiling erpcgen.exe

# Pull request

**Choose Correct**

- [X] bug
- [ ] feature

**Describe the pull request**

see issue #314 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:Windows
- eRPC Version:1.8.1

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [x] I read Contribution details and did appropriate actions.
- [X] PR code is tested. In windows system only
- [x] PR code is formatted.
- [x] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by amgross** [comment]
The greeting failure is not related to me I suppose.
Do the other failure in the CI is related to my change or bug in the CI?

**Comment by Hadatko** [comment]
Hi @amgross , i would like to keep this and found workround for you. Could you post more information? Bison version and is it from this site? https://sourceforge.net/projects/winflexbison
Maybe we need update that line to something else...

**Comment by amgross** [comment]
hi @Hadatko .It is the one available now at https://sourceforge.net/projects/winflexbison
I suppose it is latest

**Comment by Hadatko** [comment]
@amgross your version looks old if you download the on that page directly. Could you try use version3 from same link under files?
`https://sourceforge.net/projects/winflexbison/files/win_flex_bison3-latest.zip/download`

**Comment by Hadatko** [comment]
Thank you and let us know. In this case we will just update Readme. Otherwise we will need to fix it somehow differently. But the issue you are mentioning looks be connected to bison version.

**Comment by amgross** [comment]
With it getting 'configuration 'Debug|Win32'. IntelliSense might be unavailable.' error.

Whatever.

**Pull request closed without merging**
