### PR TITLE
Erpcgen py union type

### PR DESCRIPTION
**Pull request by zuzy**
Fix erpcgen python inout, union, type bug

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @zuzy , thank you for this PR, please give me some time to review and evaluate. Thank you.

**Comment by MichalPrincNXP** [comment]
Hello @zuzy , I have looked at the first commit of this PR and it seems to be OK. I agree with modifications of the callback test but it needs to be rebased to the current head of develop branch and to resolve minor conflicts in test_callbacks_server_impl.cpp.
As for the rest of commits which are python-related, I would ask @Hadatko for the review (consultation with Tomas). 
Anyway, there are several changes to be done in these last two python-related commits:
- test_length_py.yml, test_name_py.yml and test_union_py.yml need to be updated to pass erpcgen py tests
- "LOG_DEBUG" in PythonGenerator.cpp needs to be replaced by "Log::debug"

**Comment by zuzy** [comment]
> Hello @zuzy , I have looked at the first commit of this PR and it seems to be OK. I agree with modifications of the callback test but it needs to be rebased to the current head of develop branch and to resolve minor conflicts in test_callbacks_server_impl.cpp.
> As for the rest of commits which are python-related, I would ask @Hadatko for the review (consultation with Tomas).
> Anyway, there are several changes to be done in these last two python-related commits:
> 
> * test_length_py.yml, test_name_py.yml and test_union_py.yml need to be updated to pass erpcgen py tests
> * "LOG_DEBUG" in PythonGenerator.cpp needs to be replaced by "Log::debug"

Hello @MichalPrincNXP @Hadatko  , thanks for reviewing. 
I ignored the test in erpcgen before. Now they get fixed.

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by MichalPrincNXP** [comment]
Thank you, @zuzy 
Michal

**Pull request merged**
