### PR TITLE
Fixed rpmsg tty transport to work with serial transport

### PR DESCRIPTION
**Pull request by Hadatko**
Ability to receive message in two buffers

# Pull request

**Choose Correct**

- [x] bug
- [ ] feature

**Describe the pull request**

https://github.com/EmbeddedRPC/erpc/issues/372

**To Reproduce**

send message from serial side to rpmsg tty side.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [x] I checked if other PR isn't solving this issue.
- [x] I read Contribution details and did appropriate actions.
- [x] PR code is tested.
- [ ] PR code is formatted.
- [ ] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
@MichalPrincNXP This should be ready for merge.

**Comment by amgross** [comment]
Just curious, why the casting to void of functions needed (for example the memcpy)?

I know that doing it to variables is for 'dummy' readings them, but why reading their return code needed?

**Comment by Hadatko** [comment]
Hi @amgross , for example when you have misra, it will complain that you don't check for return values (same like variable which is not used). This way you are informing compiler that you are doing it on purpose.

**Comment by Hadatko** [comment]
I think this is ready. Can you review it @MichalPrincNXP ?

**Review by MichalPrincNXP — APPROVED** [review]
Seems to be ok, but I am not able to try it on any example. Did you have a chance to try it in any erpc app?

**Comment by MichalPrincNXP** [comment]
I see, ok, we can accept that. Thank you.

**Pull request merged**
