### PR TITLE
fix for issue 420:  UART ZEPHYR Transport will (most likely) stop to work after a few transactions when using USB-CDC

### PR DESCRIPTION
**Pull request by rene-becker-setec**
fixes issue 420.

fixes: https://github.com/EmbeddedRPC/erpc/issues/420

# Pull request

## Choose Correct

- [x ] bug
- [ ] feature

## To Reproduce

see  https://github.com/EmbeddedRPC/erpc/issues/420

## Expected behavior
see https://github.com/EmbeddedRPC/erpc/issues/420

## Screenshots
N/A

## Desktop (please complete the following information):

see https://github.com/EmbeddedRPC/erpc/issues/420

## Steps you didn't forgot to do

- [ x] I checked if other PR isn't solving this issue.
- [ x] I read Contribution details and did appropriate actions.
- [ x] PR code is tested.
         But only on my HW setup ...
- [ x] PR code is formatted.
- [ ] Allow edits from maintainers pull request option is set (recommended).
       Can't set this option - I think because the fork is owned by my org, not me as individual

## Additional context

N/a

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @rene-becker-setec , thank for preparing this PR, it looks good ... could you format the code as per results of https://github.com/EmbeddedRPC/erpc/actions/runs/8588230594/job/23746634738?pr=421  or to allow the editing for me to do so? Thank you
Michal

**Comment by rene-becker-setec** [comment]
> Hello @rene-becker-setec , thank for preparing this PR, it looks good ... could you format the code as per results of https://github.com/EmbeddedRPC/erpc/actions/runs/8588230594/job/23746634738?pr=421  or to allow the editing for me to do so? Thank you
> Michal

Hi @MichalPrincNXP ,
Done. 
Would give you editing access if I could figure out how to. 
Cheers, 
Rene

**Comment by MichalPrincNXP** [comment]
> > Hello @rene-becker-setec , thank for preparing this PR, it looks good ... could you format the code as per results of https://github.com/EmbeddedRPC/erpc/actions/runs/8588230594/job/23746634738?pr=421  or to allow the editing for me to do so? Thank you
> > Michal
> 
> Hi @MichalPrincNXP , Done. Would give you editing access if I could figure out how to. Cheers, Rene


I am still not able to edit, please use this formatted version:
[erpc_uart_zephyr_transport.zip](https://github.com/EmbeddedRPC/erpc/files/14959263/erpc_uart_zephyr_transport.zip)

**Comment by rene-becker-setec** [comment]
> > > Hello @rene-becker-setec , thank for preparing this PR, it looks good ... could you format the code as per results of https://github.com/EmbeddedRPC/erpc/actions/runs/8588230594/job/23746634738?pr=421  or to allow the editing for me to do so? Thank you
> > > Michal
> > 
> > 
> > Hi @MichalPrincNXP , Done. Would give you editing access if I could figure out how to. Cheers, Rene
> 
> I am still not able to edit, please use this formatted version: [erpc_uart_zephyr_transport.zip](https://github.com/EmbeddedRPC/erpc/files/14959263/erpc_uart_zephyr_transport.zip)

OK, updated file with the one you supplied.
Reading GitHub documentation it looks like I am not able to 'allow editing' as my fork is organization owned, not individually. Will have to use a different method next time.

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by MichalPrincNXP** [comment]
Thank you.

**Pull request merged**
