### PR TITLE
Add mbed os support

### PR DESCRIPTION
**Pull request by AGlass0fMilk**
Add support to use erpc with Mbed-OS.

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @AGlass0fMilk , please rebase to the head of the develop branch (1.7.3 version) and follow instructions about code formatting as described here: https://github.com/EmbeddedRPC/erpc/wiki/Contributing (avoid using tabs).
Also, could you point to an example project with mbedOS that we could use for build testing? Thanks.

**Comment by AGlass0fMilk** [comment]
Hi @MichalPrincNXP,

I rebased with the current head of the develop branch and I reformatted my changes to remove tabs.

You can find example projects using MbedOS here: https://github.com/EmbeddedPlanet/mbed-rpc

**Comment by MichalPrincNXP** [comment]
Hi @AGlass0fMilk,
your pull request looks good. We prefer the PR integration into the develop branch first, the main branch should be used for main releases. I have added this note into the https://github.com/EmbeddedRPC/erpc/wiki/Contributing As per this, could you please rebase your PR to the develop branch?
As for the mbedOS app. build testing, this would require certain effort to setup the build environment on our side. Because it is out of our focus now we can accept your PR, supposing you have tested the mbedOS port in your project. Once there are any issues reported to the mbedOS port we will route them to you. Are you OK? 
Another way how to ensure mbedOS build testing is the Travis. Would you be able to prepare erpc project .travis.yml update to add an mbedOS erpc app build? This could be done as a separate PR. Thanks.

**Comment by MichalPrincNXP** [comment]
Hello @AGlass0fMilk , did you have a chance to read my last comment? Thank you.

**Comment by AGlass0fMilk** [comment]
Hi @MichalPrincNXP. Yes I will rebase soon. This is again relevant to customer projects so I'll be able to devote some more time to it.

I can look into setting up the travis as well.

**Comment by AGlass0fMilk** [comment]
@MichalPrincNXP I rebased this PR to develop, can you review?

**Comment by MichalPrincNXP** [comment]
Thank you @AGlass0fMilk for rebasing, your pull request looks good and could be merged.
Once there is any question about mbedOS support it will be routed to you as stated in my previous comment. It would be also good if you could invest time to the Travis update, preparing another pull request.

**Comment by MichalPrincNXP** [comment]
@AGlass0fMilk , I have missed that the correct name of the added cpp files should be erpc_threading_mbed.cpp (instead of erpc_port_mbed.cpp) to be aligned with other port layer files naming. Just note, that I will do the renaming. 
Any progress on the Travis?
Thanks.

**Pull request merged**
