### PR TITLE
Removed boost dependency

### PR DESCRIPTION
**Pull request by Hadatko**
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

# Pull request

**Choose Correct**

- [ ] bug
- [X] feature

**Describe the pull request**

Newer c++ allow us to build app without boost library dependency. This is simplifying dependencies and build time.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [x] I read Contribution details and did appropriate actions.
- [X] PR code is tested.
- [X] PR code is formatted.
- [X] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
I need test compilation under VSC

**Comment by Hadatko** [comment]
@MichalPrincNXP compilation under VS works for me for debug and release

**Review by MichalPrincNXP — APPROVED** [review]
works fine on my side as well, PlatformToolset changed to v142 as agreed via email

**Comment by MichalPrincNXP** [comment]
Thank you for the effort!

**Pull request merged**
