### PR TITLE
Feature Threading support for ThreadX

### PR DESCRIPTION
**Pull request by ierturk**
In this PR includes
- Azure RTOS ThreadX threading support (Thread, Mutex, Semaphore)
- Building the library with CMake

Test configuration
- Nucleo STM32H743ZI2 board as rpc server over UART transport @ 115200 Baud, 8n1
- Toradex iMX8m Mini SOM DK (Torizon/Yocto Linux) as rpc client over serial transport @ 115200 Baud, 8n1

### CODE REVIEW

**Comment by Hadatko** [comment]
Hi and thank you very much for new OS port. Amazing.

**Comment by ierturk** [comment]
Thank you for your comment @Hadatko

**Review by MichalPrincNXP — COMMENTED** [review]
Hello @ierturk ,
thanks for this ThreadX support for the eRPC. In general, it looks fine. Here are my comments:
- you are using erpc_port_stdlib.cpp in the cmake file but erpc_port_threadx.cpp (missing in erpc_c\port) should be used/created (like for other OSes)
- I am not sure about adding the cmake file, we have not been supporting them since now, did you have a chance to use make/makefile? @Hadatko what is your opinion on that?
- similar to #81 , we are not able to test and maintain the ThreadX support, are you OK with routing community questions/issues about ThreadX support to you to be addressed?

Thank you
Michal

**Comment by Hadatko** [comment]
Hi, i am not against CmakeList usage. Many people were requesting CMakeList instead of Makefiles. But origin author was against CmakeLists usage. But i don't remember a reason.

**Comment by ierturk** [comment]
Hi @MichalPrincNXP,
 Thanks for the review. Please find the answer under your comment. 

* you are using erpc_port_stdlib.cpp in the cmake file but erpc_port_threadx.cpp (missing in erpc_c\port) should be used/created (like for other OSes)
    
    In my case, using the `erpc_port_stdlib.cpp` doesn't cause any problem. However I can add a separate port file for `ThreadX`.  

* I am not sure about adding the cmake file, we have not been supporting them since now, did you have a chance to use make/makefile? @Hadatko what is your opinion on that?
    
    You can simply ignore it if it cause any inconvenience. Also no need a Makefile because it is not related with Linux/Windows OS tools.

* similar to #81 , we are not able to test and maintain the ThreadX support, are you OK with routing community questions/issues about ThreadX support to you to be addressed?

    Yes, I am. If you are OK, you can forward any issue related the `ThreadX` support.

Thanks and regards,
Ibrahim

**Comment by MichalPrincNXP** [comment]
Hello @ierturk , thanks for the response and the commitment to handle ThreadX-related questions/issues. As for erpc_port_threadx.cpp I would prefer to add it. As for CmakeList, I would prefer to remove it as it is not systematic when there is no generic Cmake support now. We can decide later to support it, ok? Could you please prepare the PR update? Once done I will merge this PR. Thank you.

**Comment by ierturk** [comment]
Hi @MichalPrincNXP,
I'll update the PR as per your request and let you know. I'll remove the CMakeList file and create a separate port file.
Regards.

**Comment by ierturk** [comment]
Hi @MichalPrincNXP,
I've already modifed source as per your request, tested on my hardware and updated the PR.
Regards,
Ibrahim

**Review by MichalPrincNXP — APPROVED** [review]
Thank you very much, will integrate it.

**Pull request merged**
