### PR TITLE
erpcgen: Fix templates for malloc errors.

### PR DESCRIPTION
**Pull request by AdithyaBaglody**
If during the execution of the code the malloc fails to allocate
memory, appropriate checks are needed for safe execution.
This patch introduces new checks to ensure safe execution.

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Hello @AdithyaBaglody , the situation with memory allocation checking is not ideal, I agree. However, your pull request solves structures only and that is not systematic to cover just one of all possible data types. Would you be willing to update the patch and cover all supported cases? Also, it is necessary to follow the coding style and not putting if conditional statements on a single line - instead it is required to use curly brackets and put the command in it. Thank you.

**Comment by AdithyaBaglody** [comment]
> Hello @AdithyaBaglody , the situation with memory allocation checking is not ideal, I agree. However, your pull request solves structures only and that is not systematic to cover just one of all possible data types. Would you be willing to update the patch and cover all supported cases? Also, it is necessary to follow the coding style and not putting if conditional statements on a single line - instead it is required to use curly brackets and put the command in it. Thank you.

@MichalPrincNXP I did some changes in the patch to conform to the coding standards. Also i have added a few more conditions for other data types aswell. I did a few cases and saw all the malloc'd variables were protected. Since i am not familiar with all the supported cases, i am not sure how much i can help in getting them fixed.

**Comment by AdithyaBaglody** [comment]
@MichalPrincNXP hi did you get a chance to review these changes?

**Comment by MichalPrincNXP** [comment]
Hello @AdithyaBaglody , I am sorry for delayed response ... looking at your pull request again, I have several comments:
a. It is better to add new changes in new commit instead of modifying the previous commit and pushing it with --force, it helps to better understand the development history ...
b. Taking an example from [test_unions](https://github.com/EmbeddedRPC/erpc/tree/develop/test/test_unions): there is ArithmeticService_service::sendMyFoo_shim that allocates structure _f_ and even the allocation fails it passes null pointer to read_foo_struct() function. This is not acceptable and your changes in c_common_functions.template solve that by adding null pointer checker at the read_foo_struct() function beginning. I am ok with accepting these changes.
c. But, I am afraid adding "if (!codec->getStatus())" checkers in other parts is not necessary. Looking at the read_foo_struct() again, it would be like this: 
image
i.e. "if (!codec->getStatus())" checkers are called repeatedly and I do not see the necessity. Could you please elaborate your motivation for this change, any case you are dealing with?
d. As for Travis check fail, this is caused by python erpcgen test, pattern 'codec\->getStatus\(\)' is not expected in test case: test_error_checks_c.yml::not_allowed::type12_in and in test case: test_error_checks_c.yml::not_allowed::type13_out. This is aligned with point c.

Regards
Michal

**Comment by Hadatko** [comment]
Hi, i reviewed the changes. I reverted changes which where not related to return from struct/union read/write functions when data are NULL. 
Quickly it looked like not an issue. If you steel see some case as an issue please create new PR where case is described.

**Comment by Hadatko** [comment]
Thank you for your contribution. Your changes can be still found on your branch in history before my commits.

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by MichalPrincNXP** [comment]
Thank you!

**Pull request merged**
