### PR TITLE
Pr multiple idl files

### PR DESCRIPTION
**Pull request by dpfrey**
When trying to add a second `.erpc` IDL file into our project, we found two problems.

1) When trying to include two `*_server.h` header files, the same `#ifndef/#define ERPC_TYPE_DEFINITIONS/#endif` was used to guard the definition of different types.  As a result, the types enclosed in this `#ifndef` in the second header file included were being hidden.  The solution I came up with was to put the filename of the IDL file into the `#ifdef`.

2) The help information for erpcgen indicated that it supported passing multiple `.erpc` files, but the implementation only processed the first file.  I added a change to loop over all files passed to erpcgen.  I believe this is necessary because if `erpcgen` is invoked once per `.erpc` file, it seems that the service IDs are re-used.

### CODE REVIEW

**Comment by Hadatko** [comment]
Hi, thank you for your PR. Could you create and send short example of erpc files to demonstrate your use case?

**Comment by dpfrey** [comment]
@Hadatko: I have provided an example that demonstrates the issue here: https://github.com/dpfrey/erpc_examples/tree/master/two_interfaces

You should be able to run something like this to build it: `ERPC_ROOT=~/sw/erpc/f2787e8b0e6f46eb6df6dea3e6c34213256a8faa make`, but you will require the commits from this PR in order to build it successfully.

**Comment by MichalPrincNXP** [comment]
@dpfrey , have you tried to use the @group annotation as described at https://github.com/EmbeddedRPC/erpc/wiki/IDL-Reference and used in https://github.com/EmbeddedRPC/erpc/blob/develop/test/test_arbitrator/test_arbitrator.erpc ? @Hadatko , what was the original intention, using the @group annotation or supporting multiple eprc files being provided via the command line? The only reference about supporting multiple files on the command line is the one from the erpcgen help display:
usage: erpcgen.exe [-?|--help] [-V|--version] [-o|--output <filePath>]
                   [-v|--verbose] [-I|--path <filePath>]
                   [-g|--generate <language>] [-c|--codec <codecType>] **files...**
Thanks.

**Comment by dpfrey** [comment]
My thinking was that it would make sense to be able to define unrelated APIs in different IDL files. I guess I could just put the unrelated definitions into the same file, but that seems worse from the perspective of trying to keep things organized.

**Comment by Hadatko** [comment]
Hi, did you consider include erpc1.idl file in erpc2.idl file?

**Comment by Hadatko** [comment]
I would close this PR due to wrong usage of erpc files.
Sorry for obstruction.

**Comment by MichalPrincNXP** [comment]
agree

**Pull request closed without merging**
