### PR TITLE
Feature/static allocation

### PR DESCRIPTION
**Pull request by Hadatko**
More static memory usage possibility (still shim code not fully supporting and not all transports are using new macros).
PR which should be merged after these: #153  #168

### CODE REVIEW

**Comment by MichalPrincNXP** [comment]
Thank you, Dusan, quite massive changes to be reviewed and tested, let's target these changes for the next release (after v1.8.1 release), ok? Thanks.

**Comment by Hadatko** [comment]
Hi @MichalPrincNXP , yes sure ;)

**Comment by Hadatko** [comment]
It looks like i need fix merge conflicts

**Comment by MichalPrincNXP** [comment]
After merging this PR with #168 and using rpmsg_lite with updated static allocations, I got my erpc_matrix_multiply_rpmsg_rtos example running. @Hadatko what way of integrating all into the mainline do you prefer? Thank you.

**Comment by Hadatko** [comment]
@MichalPrincNXP That is great. Sorry i don't know what you are asking for. Normal procedure is fine for us (review and merge into develop branch)

**Comment by Hadatko** [comment]
I see conflicts, i can resolve them. Not sure if Manually constructed changes PR was merged.

**Comment by Hadatko** [comment]
Conflicts should be solved.

**Review by MichalPrincNXP — APPROVED** [review]
This PR is linked with #168  and will be integrated together. Nevertheless, this does not allow static allocation of all erpc objects and the work on the static allocations needs to continue (information for others looking at this PR). "Known issues and limitations" section should be added into the wiki with following statement:
Static allocations controlled by the ERPC_ALLOCATION_POLICY config macro are not fully supported yet, i.e. not all erpc objects can be allocated statically now. It deals with the ongoing process and the full static allocations support will be added in the future.

**Comment by MichalPrincNXP** [comment]
Thank you for the effort!

**Pull request merged**
