### PR TITLE
Move enums to enum classes

### PR DESCRIPTION
**Pull request by Hadatko**
# Pull request

**Choose Correct**

- [ ] bug
- [x] feature

**Describe the pull request**

This PR is moving enums from global scope to class scope. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- eRPC Version:

**Steps you didn't forgot to do**

- [X] I checked if other PR isn't solving this issue.
- [X] I read Contribution details and did appropriate actions.
- [X] PR code is tested.
- [X] PR code is formatted.
- [ ] Allow edits from maintainers pull request option is set (recommended).

**Additional context**

### CODE REVIEW

**Comment by Hadatko** [comment]
@MichalPrincNXP i think this is ready to merge. Can you review it?

**Comment by Hadatko** [comment]
Closed by mistake ;) @MichalPrincNXP waiting for review

**Review by MichalPrincNXP — APPROVED** [review]
Performed on-board testing and all seems to be ok.

**Comment by MichalPrincNXP** [comment]
Thank you.

**Pull request merged**
