### PR TITLE
Fix timeout for Freertos semaphore.

### PR DESCRIPTION
**Pull request by Hadatko**
It doesn't make sense to have portMaxDelay and then recalculate to lower value. Currently other ports are using simple implementation so i align with that.

Signed-off-by: Cervenka Dusan <cervenka@acrios.com>

### CODE REVIEW

**Comment by Hadatko** [comment]
Old PR is no more valid as it is in archived repository: https://github.com/EmbeddedRPC/erpc/pull/34
It looks like the request is to use full scale timer. Currently all ports are independent and unit is not set.
I think original unit was in us. If we want use common unit we need align all ports.

@MichalPrincNXP what do you think? Maybe we need talk about it more.

**Comment by Hadatko** [comment]
We can also have other function which will count "us" based on OS. But i don't know if it will not be too much complicated, but OS like this would have possibility to use full scale timer. Maybe have two functions. get() (OS indenpendet) and getUs() /*get in us*/

**Comment by Hadatko** [comment]
@MichalPrincNXP now it should be aligned. Do you see any error in code? Most of them i cannot test.

**Review by MichalPrincNXP — COMMENTED** [review]
It looks good to me. The only thing I would change is the name of the get function parameter, it should stay clear that it deals with timeout, so my proposal is to change it to timeout_usecs. This parameter name should be also changed in erpc_threading_pthreads.cpp to have it unified. Thank you.

**Comment by Hadatko** [comment]
Hi @MichalPrincNXP, is it ok now?

**Review by MichalPrincNXP — APPROVED** [review]

**Comment by MichalPrincNXP** [comment]
Thanks, Dusan!

**Pull request merged**
